app:
    resource: '@AppBundle/Controller/'
    type: annotation

form:
    path:     /form
    defaults: { _controller: AppBundle:Default:form }
    
title:
    path:      /result
    defaults: { _controller: AppBundle:Default:title }
    

    
sandbox_pdfexample:
    path:     /pdf
    defaults: { _controller: AppBundle:Default:pdf }    


    
   